apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo
  name: mongo-svc1
spec:
  type: NodePort
  ports:
    - port: 27017
      nodePort: 31017
      name: mongo-port
  selector:
    type: mongo-rs-A

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo
  name: mongo-svc2
spec:
  type: NodePort
  ports:
    - port: 27017
      nodePort: 31027
      name: mongo-port 
  selector:
    type: mongo-rs-B

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo
  name: mongo-svc3
spec:
  type: NodePort
  ports:
    - port: 27017
      nodePort: 31037
      name: mongo-port
  selector:
    type: mongo-rs-C

