apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-single      
spec:
  replicas: 1          
  selector:
    app: redis-single
  template:
    metadata:
      labels:
         app: redis-single  
    spec:
      containers:
      - name: redis-single
        image: 10.1.245.4:5000/redis:3.2.1
        ports:
        - containerPort: 6379
        env:
        - name: START_MODE
          value: single
        - name: REDIS_PORT
          value: "6379"
        - name: MAX_MEM
          value: "64m"
        - name: PASSWORD
          value: "123456"


