apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-sentinel-slave
spec:
  replicas: 1
  selector:
    name: redis-sentinel-slave
  template:
    metadata:
      name: redis-sentinel-slave
      labels:
        name: redis-sentinel-slave
    spec:
      hostNetwork: true
      containers:
      - name: redis-sentinel-slave
        image: 10.1.245.4:5000/redis:3.2.1
        ports:
        - containerPort: 56379
        env:
        - name: START_MODE
          value: replication
        - name: REDIS_PORT
          value: "56379"
        - name: MAX_MEM
          value: "64m"
        - name: MASTER_PORT
          value: "56379"
        - name: PASSWORD
          value: "123456"

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-sentinel
spec:
  replicas: 1
  selector:
    name: redis-sentinel
  template:
    metadata:
      name: redis-sentinel
      labels:
        name: redis-sentinel
        redis-sentinel: "true"
    spec:
      hostNetwork: true
      containers:
      - name: redis-sentinel
        image: 10.1.245.4:5000/redis:3.2.1
        ports:
        - containerPort: 26379
        env:
        - name: START_MODE
          value: sentinel
        - name: REDIS_PORT
          value: "26379"
        - name: MAX_MEM
          value: "64m"
        - name: MASTER_PORT
          value: "56379"
        - name: PASSWORD
          value: "123456"
