apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-master
spec:
  replicas: 1
  selector:
    name: redis-master
  template:
    metadata:
      name: redis-master
      labels:
        name: redis-master
    spec:
      containers:
      - name: redis-master
        image: 10.1.245.4:5000/redis:3.2.1
        ports:
          - containerPort: 6379
        env:
          - name: START_MODE
            value: master
          - name: REDIS_PORT
            value: "6379"
          - name: MAX_MEM
            value: "64m"
          - name: PASSWORD
            value: "123456"

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-slave
spec:
  replicas: 2
  selector:
    name: redis-slave
  template:
    metadata:
      name: redis-slave
      labels:
        name: redis-slave
    spec:
      containers:
      - name: redis-slave
        image: 10.1.245.4:5000/redis:3.2.1
        ports:
        - containerPort: 6379
        env:
        - name: START_MODE
          value: replication
        - name: REDIS_PORT
          value: "6379"
        - name: MAX_MEM
          value: "64m"
        - name: MASTER_IP
          value: "redis-master"
        - name: MASTER_PORT
          value: "6379"
        - name: PASSWORD
          value: "123456"
